swagger: '2.0'
info: 
  title: Apostle music app server API Documentation
  description: API documentation for Apostle music app.
  version: 1.0
  contact: 
    email: successakinyemi365@gmail.com
  license:
    name: Apache 2.0
    url: 'http://apache.org/'
host: apostle.onrender.com
basePath: /               
schemes:
  - https