swagger: '2.0'
info: 
  title: Edu-connect, ACN, Arewa Hub server API Documentation
  description: API documentation for Edu-connect, ACN, Arewa Hub.
  version: 1.0
  contact: 
    email: successakinyemi365@gmail.com
  license:
    name: Apache 2.0
    url: 'http://apache.org/'
host: educonnect-admin-backend.onrender.com
basePath: /               
schemes:
  - https

paths:
  /:
    get:
      summary: Home GET request
      description: Server base endpoint
      responses:
        200:
          description: Success

  /api/educonnect/contactUs/sendMessage:
    post:
      summary: send a contact us message
      description: send a contact us message
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - firstName
              - lastName
              - email
              - phoneNumber
              - message
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              phoneNumber:
                type: string
              message:
                type: string
      responses:
        201: 
          description: Message Submitted Successful
        400:
          description: User error
        500: 
          description: Server error

  /api/educonnect/faq/getAllFaq:
    get:
      summary: Get Faq for educonnect
      description: get frequently asked questions for educonnect website
      responses:
        200:
          description: Success
        500:
          description: Server error 

  /api/acn/contactUs/sendMessage:
    post:
      summary: send a contact us message
      description: send a contact us message
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - firstName
              - lastName
              - email
              - phoneNumber
              - message
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              phoneNumber:
                type: string
              message:
                type: string
      responses:
        201: 
          description: Message Submitted Successful
        400:
          description: User error
        500: 
          description: Server error

  /api/acn/faq/getAllFaq:
    get:
      summary: Get Faq for educonnect
      description: get frequently asked questions for educonnect website
      responses:
        200:
          description: Success
        500:
          description: Server error 

  /api/testimony/getSectionActiveTestimonies/:value:
    get:
      summary: Get Testimonies form testifiers
      description: Get Testimonies form testifiers value parameters = 'educonnect', 'acn', 'arewahub'
      responses:
        200:
          description: Success
        400:
          description: User error
        500:
          description: Server error 

  /api/suscribe/addSuscriber:
    post:
      summary: Add user to news letter
      description: This endpoint add user to newdletter list. requires user email, and website to identify the website user want to subscribe to website value options = ['educonnect', 'acn', 'arewahub']
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            required:
              - email
              - website
            properties:
              email:
                type: string
              website:
                type: string
      responses:
        201: 
          description: Successful
        400:
          description: User error
        500: 
          description: Server error
